### ISSUE TITLE
CORS 跨域资源读取漏洞

### ISSUE THREAD

**Issue by shuinger** [wangzmgit/leaf#38]
通用修复建议：
1.禁止配置“Access-Control-Allow-Origin”为“*”和“null”；
2.严格校验“Origin”值，避免出现权限泄露；
3.避免使用“Access-Control-Allow-Credentials:true”；
4.减少“Access-Control-Allow-Methods”所允许的方法。
Nginx 设置 CORS 实现跨域访问
默认情况下 Ajax 在请求跨域的时候会被阻止，如调用 API/前端库字体等不方便，可通过如下设置来实现跨域访问。
Nginx 配置
在 nginx server 段内添加如下代码，并重启 Nginx 即可：
location /{
add_header 'Access-Control-Allow-Origin' ip 地址;
add_header 'Access-Control-Allow-Credentials' 'true';
add_header 'Access-Control-Allow-Headers'
'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Con
trol,X-Mx-ReqToken,X-Requested-With';
add_header 'Access-Control-Allow-Methods' 'GET,POST';
}
注意：add_header 'Access-Control-Allow-Origin' ip 地址 需要进行指定ip 配置。

**Comment by wangzmgit** [comment]
感谢报告，目前在后端增加了对Access-Control-Allow-Origin的配置，减少了Access-Control-Allow-Methods所允许的方法。
