### ISSUE TITLE
似乎无法通过点击个人中心->我的视频中的修改信息来修改视频的信息

### ISSUE THREAD

**Issue by Lie-bang** [wangzmgit/leaf#51]
我在我的电脑上运行了它，但是似乎无法通过点击个人中心->我的视频中的修改信息来修改视频的信息，这样做的结果只是打开上传一个新视频的页面。但是当视频审核失败的时候可以进入修改视频信息页面。

**Comment by Lie-bang** [comment]
我明白，我是在审核结束后点击修改的，它出现了修改信息与修改视频的框，但是点击修改信息就会出现上传视频的状态，而点击修改视频则一切正常，可以修改

**Comment by wangzmgit** [comment]
确实是个Bug，修复了，重新拉取一下代码就可以了
