### ISSUE TITLE
发现的一些bug和建议

### ISSUE THREAD

**Issue by baka-9** [wangzmgit/leaf#84]
**Bug（这些是在我部署中遇到的，不清楚是不是我的问题）:**
1.有些视频上传之后频繁显示上传失败，而有些视频却可以，初步推测是编码转换问题

2.后台的审核界面查看不了视频，而且在查看视频的地方点击通过却不能通过，必须退出点上一层的通过按钮

3.无论什么视频最后预览界面的比例都是16：9，这导致所有非16：9的视频最后都会被拉伸为16：9，就比如把人物拉伸成宽体的

4.发送验证码的邮件显示不了html正确格式
具体表现为
`<h3>尊敬的用户：</h3><p>您好! 您的验证码是 <span style='color:red'> xxxx</span>，五分钟内有效，祝您生活愉快！</p>`

5.UID顺序不连贯，管理员UID为1注册的新账户UID为6（不知道是不是我的问题

**建议：**
1.支持9：16等多比例视频适配

2.云存储方面支持AWS S3协议，大部分小厂的对象存储都适配的是这个协议

3.多格式视频，比如flv，更好的压缩下视频体积更小

4.增加转码速度，比如使用ffmpeg

5.增加类似b站的硬币系统OWO

---
**最后，非常感谢您创建并持续维护这个项目，祝您健康幸福！**

**Comment by wangzmgit** [comment]
该项目已经停止更新了，即将发布新版本，如果有兴趣可以加入新版本的开发。（已发送新版仓库的邀请）

**Comment by baka-9** [comment]
好的，谢谢QWQ
